# Generated by Django 3.2.2 on 2021-05-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_video_url_lesson_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
    ]
